### ISSUE TITLE
New plugin not loaded without restarting editor on Ubuntu

### ISSUE THREAD

**Issue by mikkomcmenamin** [MCpiroman/UnityNativeTool#26]
Hi, 

I'm on Ubuntu 18.04 and using Unity 2019.4. When I build my plugin into the Plugins folder when my editor is open, the DllManipulator still loads the old .so, even if do the "unload all dlls" and load commands. Only by restarting the editor it loads the newly built one.  
 
I followed the instructions and checked that I have all these set up properly: 
- Api Compatibility Level to .NET 4.
- Allow 'unsafe' code.
- DllManipulatorScript in active scene
- underscores before plugin name 
- Execution order

Any idea why it's not working?

**Comment by mcpiroman** [comment]
If what you do is:
- Load the plugin
- Unload the plugin
- Replace the plugin's file with a new version
- Load the plugin again

Then I have little idea how it could possibly load the old, now not existing one. Maybe it actually fails to unload and when you  do a rebuild, your toolchain succeeds to generate new binary but fails to copy it into unity? Or something of that nature. Try to replace the file manually. Are you also sure there aren't any errors in the console?

Apart from that, it'd be best if you could provide me with some repro project so I can test that.

**Comment by mikkomcmenamin** [comment]
Tried replacing it manually, but it still loads the old version. Only thing that works is restarting the editor. I guess it might have something to do with the actual plugin functions. Maybe it's failing on some when it's mocking them (not really sure how this works). 

I'll try again later with a very simple plugin to see if it still doesn't work. 

Loading and Unloading the plugin is a bit unclear to me still. Isn't it supposed to load the plugins  while starting Play and unloading when ending play? I also tried the shortcuts and buttons that appear in the UnityNativeTool editor window when playing.

**Comment by mikkomcmenamin** [comment]
Ok, that was exactly the case. Some of the export functions were not supported I guess and even though I wasn't using them, they caused problems and affected loading of the plugin. Now that I stripped the plugin clean from possibly problematic export functions it seems to work. 

Thanks!

**Comment by mcpiroman** [comment]
Well, I'm interested to see which of the functions are causing the problem, because if they don't apply to the limitations section (don't they?) it should work fine.

> Loading and Unloading the plugin is a bit unclear to me still. Isn't it supposed to load the plugins while starting Play and unloading when ending play?

Yes, that's what happens automatically (actually, with `Lazy` mode it loads them not just when you hit play but when they are first called, which can be more flexible). The additional buttons and shortcuts are provided if you want to do some more subtle stuff like reloading while playing or when using native functions in custom editors.
