### ISSUE TITLE
Unity crash when using "open mp" in native dll.

### ISSUE THREAD

**Issue by CharlesQHappy** [MCpiroman/UnityNativeTool#30]
Hi, when I used omp- code in my native dll, each time I stop the playing, Unity will crash. But, if I click "pause" button first, then stop the playing, Unity will be ok.
How's that?

**Comment by mcpiroman** [comment]
Weird.. I can't imagine how pausing before stopping could affect anything. 
Ofc I'd need more info from you, like Unity's crash logs, versions, OS, configuration (from `DllManipulatorScript`). Do you (or the lib) use any threading? Is your code which calls dll more 'simpler' or 'complexier'? For the letter you could also provide relevant samples, if you think they'd be meaningful.
