### ISSUE TITLE
native rendering plugins

### ISSUE THREAD

**Issue by JeffBail** [MCpiroman/UnityNativeTool#4]
I have a native rendering plugin that works fine in the Editor but when I try to load it via UnityNativeTool it reports a NativeDllException and the Game view seems to freeze up. Is it possible to unload & reload rendering plugins or are they just tied in too tightly?

**Comment by mcpiroman** [comment]
The low-level callback functions such as `UnityPluginLoad` are not supported (they simply don't fire). I should've mentioned this in the limitations though. I might figure out a a way to handle that in the future but this should be hard enough.

If you get `NativeDllException`, then the game should not freeze but simply pause (if you use recent version of this tool) allowing you to fix the problem. Secondly, this exception should only indicate that your DLL or function that you used in managed code was not found. So e.g. make sure that you add `__` at the beginning of plugin file name.

**Comment by mcpiroman** [comment]
Good news. Apparently I did manage to get it to work with `UnityPluginLoad` (and `UnityPluginUnload`), which should be enough for most rendering plugins to work. Check out last release.

**Comment by JeffBail** [comment]
Thanks! This works great with Unity's [NativeRenderingPlugin](https://github.com/Unity-Technologies/NativeRenderingPlugin) example with 2019.1.5f1.
